### ISSUE TITLE
Not compatible with Dart 3.0 (fixed by PR #5)

### ISSUE THREAD

**Issue by JCKodel** [bamlab/equatable_lint#6]
**Description**
Using equatable_lint with some builders (for example, Isar generator) causes somehow the builder to not recognize Dart 3.0 (e.g.: it complains about syntax errors in `final class`).

The root cause for that behaviour is the old custom_lint dependency (0.2.12). Upgrading it to 0.4.0 fixes the problem.

That was done in https://github.com/bamlab/equatable_lint/pull/5

**Steps To Reproduce**

1. Use some builder + equatable_lint (custom_lint will be forced to be 0.2.12)
2. Use some Dart 3.0 features (such as new classes keywords, records or switch expressions)
3. Try to run `dart run build_runner build`
4. Those Dart 3.0 features are not recognized and issues syntax errors in builders

**Comment by Cteq3132** [comment]
Fixed by #5, thanks to @JCKodel
